name: Terraform - Prod

on:
  push:
    paths:
      - 'infra/terraform/envs/prod/**'
      - '.github/workflows/terraform-prod.yml'
    branches:
      - main

  pull_request:
    paths:
      - 'infra/terraform/envs/prod/**'
      - '.github/workflows/terraform-prod.yml'
    branches:
      - main

jobs:
  terraform:
    name: Terraform (prod)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform/envs/prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (após merge)
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: terraform apply -auto-approve
