name: Terraform - Prod

on:
  push:
    paths:
      - 'infra/terraform/envs/prod/**'
      - '.github/workflows/terraform-prod.yml'
    branches:
      - master

jobs:
  terraform:
    name: Terraform (prod)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform/envs/prod

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write GCP credentials file
        run: |
          mkdir -p ../../gcp
          echo "${{ secrets.GCP_CREDENTIALS }}" > ../../gcp/credentials.json

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan
