name: Terraform - Dev

on:
  push:
    paths:
      - 'infra/terraform/envs/dev/**'
      - '.github/workflows/terraform-dev.yml'
    branches:
      - master

jobs:
  terraform:
    name: Apply Terraform (dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/terraform/envs/dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
